const {DOMAIN_DEFINITIONS} = require('./src/data/knowledgeModel');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '开始',
      items: [
        'overview/start-here',
        'overview/journey-map',
        'overview/taxonomy',
        'overview/learning-paths',
      ],
    },
    {
      type: 'category',
      label: '知识方向',
      items: [
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS['development-modes'].label,
          items: [
            'development-modes/index',
            'development-modes/landscape',
            'development-modes/agent-execution-modes',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.workflows.label,
          items: [
            'workflows/index',
            'workflows/mainstream-ai-coding-workflows',
            'workflows/frameworks-overview',
            {
              type: 'category',
              label: '工作流模式',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflows/patterns',
                },
              ],
            },
            {
              type: 'category',
              label: '官方 / 主线工作流框架',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflows/frameworks',
                },
              ],
            },
            {
              type: 'category',
              label: '社区工作流框架',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflows/community-frameworks',
                },
              ],
            },
            'workflows/spec-driven-ai-delivery',
            'workflows/prompt-contracts',
            'workflows/bugfix-refactor-test-workflows',
            'workflows/multi-agent-collaboration',
            'workflows/workflow-catalog',
            'workflows/async-agent-delivery',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.tools.label,
          items: [
            'tools/index',
            'overview/tool-selection-map',
            'tools/resources/index',
            {
              type: 'category',
              label: '工具家族',
              items: [
                {
                  type: 'category',
                  label: '平台型工具',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/platforms',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: '控制面',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/control-planes',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: '执行栈',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/execution-stacks',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: '终端 Agent',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/terminal-agents',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'IDE-First',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/ide-first',
                    },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: '工具相关内容',
              items: [
                'comparisons/index',
                'insights/index',
                'tools/ai-ide-landscape',
                'tools/terminal-agents-and-cli',
                'tools/claude-code-workstyle',
                'tools/gemini-cli-github-workflow',
                'tools/terminal-agent-landscape',
                'tools/mainstream-tool-watchlist',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.standards.label,
          items: [
            'standards/index',
            'standards/repo-instruction-files',
            'standards/skills-commands-hooks',
            'standards/context-memory-and-rules',
            'standards/review-quality-gates',
            'standards/evaluation-risk-metrics',
            'standards/ai-development-standards',
            'standards/freshness-governance',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.architecture.label,
          items: [
            'architecture/index',
            'architecture/ai-native-engineering-architecture',
            'architecture/mcp-tool-topology',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.ecosystem.label,
          items: [
            'ecosystem/index',
            {
              type: 'category',
              label: '工具接入与治理',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'ecosystem/integrations',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '资源中心',
      items: [
        'tools/resources/index',
        'tools/resources/videos',
        'tools/resources/courses',
      ],
    },
    {
      type: 'category',
      label: '内容索引',
      items: [
        'overview/content-index',
        {
          type: 'category',
          label: 'Comparisons',
          items: [
            'comparisons/index',
            'comparisons/ai-coding-platform-comparison-framework',
            'comparisons/github-copilot-vs-vscode-agent-vs-openai-codex',
            'comparisons/cursor-vs-windsurf-vs-cline',
          ],
        },
        {
          type: 'category',
          label: 'Playbooks',
          items: [
            'playbooks/index',
            'playbooks/workflow-playbook',
            'playbooks/personal-engineer-stack-setup',
            'playbooks/first-7-days-ai-coding',
          ],
        },
        {
          type: 'category',
          label: 'Insights',
          items: [
            'insights/index',
            'insights/agentic-coding-patterns',
            'insights/monthly-brief-2026-03',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '旧赛道归档',
      items: [
        'archive/index',
        'archive/tracks/models-agents/index',
        'archive/tracks/ides-tooling/index',
        'archive/tracks/prompting-workflows/index',
        'archive/tracks/team-delivery/index',
      ],
    },
    {
      type: 'category',
      label: '站点维护',
      items: [
        'site-admin/editorial-workflow',
        'site-admin/ai-writing-workflow',
        'site-admin/publish-github',
        'site-admin/site-roadmap',
        'site-admin/example-first-note',
      ],
    },
  ],
};

module.exports = sidebars;
