const {DOMAIN_DEFINITIONS} = require('./src/data/knowledgeModel');
const toolDocNavigation = require('./src/data/toolDocNavigation.json');

function ensureString(value, fieldName) {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`Sidebar config field "${fieldName}" must be a non-empty string.`);
  }

  return value;
}

function ensureArray(value, fieldName) {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`Sidebar config field "${fieldName}" must be a non-empty array.`);
  }

  return value;
}

function validateToolDocNavigation(config) {
  const navigation = config && typeof config === 'object' ? config : null;

  if (!navigation) {
    throw new Error('Sidebar config "toolDocNavigation" must be an object.');
  }

  ensureArray(navigation.pageOrder, 'toolDocNavigation.pageOrder').forEach((page, index) => {
    ensureString(page.id, `toolDocNavigation.pageOrder[${index}].id`);
    ensureString(page.label, `toolDocNavigation.pageOrder[${index}].label`);
  });

  ['quickStartGroups', 'coreTools', 'extendedTools'].forEach((fieldName) => {
    ensureArray(navigation[fieldName], `toolDocNavigation.${fieldName}`).forEach((entry, index) => {
      ensureString(entry.id, `toolDocNavigation.${fieldName}[${index}].id`);
      ensureString(entry.label, `toolDocNavigation.${fieldName}[${index}].label`);

      if (fieldName === 'quickStartGroups') {
        ensureArray(entry.items, `toolDocNavigation.quickStartGroups[${index}].items`).forEach((item, itemIndex) => {
          ensureString(item.id, `toolDocNavigation.quickStartGroups[${index}].items[${itemIndex}].id`);
          ensureString(item.label, `toolDocNavigation.quickStartGroups[${index}].items[${itemIndex}].label`);
        });
      }
    });
  });

  return navigation;
}

const validatedToolDocNavigation = validateToolDocNavigation(toolDocNavigation);

function createToolGuideCategory(tool) {
  return {
    type: 'category',
    label: tool.label,
    link: {
      type: 'doc',
      id: `${tool.id}/index`,
    },
    items: validatedToolDocNavigation.pageOrder.map((page) => ({
      type: 'doc',
      id: `${tool.id}/${page.id}`,
      label: page.label,
    })),
  };
}

function createQuickStartCategory(group) {
  return {
    type: 'category',
    label: group.label,
    items: group.items.map((item) => ({
      type: 'doc',
      id: `${item.id}/quick-start`,
      label: item.label,
    })),
  };
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    'overview/minute-quick-start',
    'playbooks/first-7-days-ai-coding',
    'playbooks/personal-engineer-stack-setup',
    'playbooks/workflow-playbook',
    {
      type: 'category',
      label: '辅助判断',
      items: [
        'overview/start-here',
        'overview/learning-paths',
        'overview/journey-map',
        'overview/tool-selection-map',
        'overview/content-index',
      ],
    },
  ],

  resourcesSidebar: ['tools/resources/index', 'tools/resources/videos', 'tools/resources/courses'],

  toolTutorialsSidebar: [
    'tools/index',
    {
      type: 'category',
      label: '先跑 Quick Start',
      items: validatedToolDocNavigation.quickStartGroups.map(createQuickStartCategory),
    },
    {
      type: 'category',
      label: '重点工具教程',
      items: validatedToolDocNavigation.coreTools.map(createToolGuideCategory),
    },
    {
      type: 'category',
      label: '扩展工具教程',
      items: [
        ...validatedToolDocNavigation.extendedTools.map(createToolGuideCategory),
        {
          type: 'category',
          label: '判断与对比',
          items: [
            'tools/terminal-agents-and-cli',
            'tools/ai-ide-landscape',
            'tools/terminal-agent-landscape',
            'tools/mainstream-tool-watchlist',
          ],
        },
      ],
    },
  ],

  workflowTutorialsSidebar: [
    'workflows/index',
    'playbooks/workflow-playbook',
    {
      type: 'category',
      label: '先跑 Runbook',
      items: [
        'workflows/patterns/bugfix-refactor-test/runbook',
        'workflows/patterns/terminal-first-repo-pairing/runbook',
        'workflows/patterns/issue-to-draft-pr/runbook',
        'workflows/patterns/spec-first/runbook',
        'workflows/patterns/local-to-background-to-cloud/runbook',
        'workflows/patterns/parallel-worktrees-multi-agent/runbook',
      ],
    },
    'playbooks/index',
    {
      type: 'category',
      label: '重点工作流教程',
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows/patterns/bugfix-refactor-test',
        },
        {
          type: 'autogenerated',
          dirName: 'workflows/patterns/terminal-first-repo-pairing',
        },
        {
          type: 'autogenerated',
          dirName: 'workflows/patterns/issue-to-draft-pr',
        },
        {
          type: 'autogenerated',
          dirName: 'workflows/patterns/spec-first',
        },
      ],
    },
    {
      type: 'category',
      label: '扩展工作流教程',
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows/patterns/parallel-worktrees-multi-agent',
        },
        {
          type: 'autogenerated',
          dirName: 'workflows/patterns/local-to-background-to-cloud',
        },
        {
          type: 'category',
          label: '框架与方法',
          items: [
            'workflows/mainstream-ai-coding-workflows',
            'workflows/frameworks-overview',
            {
              type: 'autogenerated',
              dirName: 'workflows/frameworks',
            },
            {
              type: 'autogenerated',
              dirName: 'workflows/community-frameworks',
            },
            'workflows/multi-agent-collaboration',
            'workflows/async-agent-delivery',
            'workflows/prompt-contracts',
            'workflows/spec-driven-ai-delivery',
            'workflows/workflow-catalog',
          ],
        },
      ],
    },
  ],

  caseStudiesSidebar: [
    'case-studies/index',
    'case-studies/claude-code-bugfix-loop',
    'case-studies/gemini-cli-terminal-audit-to-draft-pr',
    'case-studies/vscode-agents-local-to-background-handoff',
    'case-studies/cline-parallel-worktree-owner-loop',
    'case-studies/windsurf-maintenance-to-pr',
    'case-studies/github-copilot-draft-pr-handoff',
    'case-studies/codex-refactor-with-verification',
  ],

  advancedTopicsSidebar: [
    {
      type: 'category',
      label: DOMAIN_DEFINITIONS.standards.label,
      items: [
        'standards/index',
        'standards/repo-instruction-files',
        'standards/skills-commands-hooks',
        'standards/context-memory-and-rules',
        'standards/review-quality-gates',
        'standards/evaluation-risk-metrics',
        'standards/ai-development-standards',
        'standards/freshness-governance',
      ],
    },
    {
      type: 'category',
      label: DOMAIN_DEFINITIONS['development-modes'].label,
      items: ['development-modes/index', 'development-modes/landscape', 'development-modes/agent-execution-modes'],
    },
    {
      type: 'category',
      label: DOMAIN_DEFINITIONS.architecture.label,
      items: ['architecture/index', 'architecture/ai-native-engineering-architecture', 'architecture/mcp-tool-topology'],
    },
    {
      type: 'category',
      label: DOMAIN_DEFINITIONS.ecosystem.label,
      items: [
        'ecosystem/index',
        {
          type: 'autogenerated',
          dirName: 'ecosystem/integrations',
        },
      ],
    },
    {
      type: 'category',
      label: '辅助导航',
      items: [
        'overview/journey-map',
        'overview/taxonomy',
        'overview/content-index',
        {
          type: 'category',
          label: '对比与观察',
          items: [
            'comparisons/index',
            'comparisons/ai-coding-platform-comparison-framework',
            'comparisons/github-copilot-vs-vscode-agent-vs-openai-codex',
            'comparisons/cursor-vs-windsurf-vs-cline',
            'insights/index',
            'insights/agentic-coding-patterns',
            'insights/monthly-brief-2026-03',
          ],
        },
      ],
    },
  ],

  archiveSidebar: [
    'archive/index',
    {
      type: 'category',
      label: '模型与 Agent',
      link: {
        type: 'doc',
        id: 'archive/tracks/models-agents/index',
      },
      items: ['archive/tracks/models-agents/coding-models-scorecard'],
    },
    {
      type: 'category',
      label: 'IDE 与工具链',
      link: {
        type: 'doc',
        id: 'archive/tracks/ides-tooling/index',
      },
      items: ['archive/tracks/ides-tooling/review-and-pr-tooling'],
    },
    'archive/tracks/prompting-workflows/index',
    {
      type: 'category',
      label: '团队与交付',
      link: {
        type: 'doc',
        id: 'archive/tracks/team-delivery/index',
      },
      items: ['archive/tracks/team-delivery/solo-to-team-transition'],
    },
  ],

  siteAdminSidebar: [
    'site-admin/editorial-workflow',
    'site-admin/ai-writing-workflow',
    'site-admin/publish-github',
    'site-admin/site-roadmap',
    'site-admin/example-first-note',
  ],
};

module.exports = sidebars;
