const {DOMAIN_DEFINITIONS} = require('./src/data/knowledgeModel');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  startSidebar: ['overview/start-here'],

  mapSidebar: [
    'overview/journey-map',
    'overview/taxonomy',
    'overview/learning-paths',
    {
      type: 'category',
      label: '知识方向',
      items: [
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS['development-modes'].label,
          link: {
            type: 'doc',
            id: 'development-modes/index',
          },
          items: ['development-modes/landscape', 'development-modes/agent-execution-modes'],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.workflows.label,
          link: {
            type: 'doc',
            id: 'workflows/index',
          },
          items: [
            'workflows/mainstream-ai-coding-workflows',
            'workflows/frameworks-overview',
            {
              type: 'category',
              label: '工作流模式',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflows/patterns',
                },
              ],
            },
            {
              type: 'category',
              label: '官方 / 主线工作流框架',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflows/frameworks',
                },
              ],
            },
            {
              type: 'category',
              label: '社区工作流框架',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'workflows/community-frameworks',
                },
              ],
            },
            'workflows/spec-driven-ai-delivery',
            'workflows/prompt-contracts',
            'workflows/bugfix-refactor-test-workflows',
            'workflows/multi-agent-collaboration',
            'workflows/workflow-catalog',
            'workflows/async-agent-delivery',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.tools.label,
          link: {
            type: 'doc',
            id: 'tools/index',
          },
          items: [
            'overview/tool-selection-map',
            {
              type: 'category',
              label: '工具家族',
              items: [
                {
                  type: 'category',
                  label: '平台型工具',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/platforms',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: '控制面',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/control-planes',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: '执行栈',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/execution-stacks',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: '终端 Agent',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/terminal-agents',
                    },
                  ],
                },
                {
                  type: 'category',
                  label: 'IDE-First',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tools/ide-first',
                    },
                  ],
                },
              ],
            },
            'tools/ai-ide-landscape',
            'tools/terminal-agents-and-cli',
            'tools/claude-code-workstyle',
            'tools/gemini-cli-github-workflow',
            'tools/terminal-agent-landscape',
            'tools/mainstream-tool-watchlist',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.standards.label,
          link: {
            type: 'doc',
            id: 'standards/index',
          },
          items: [
            'standards/repo-instruction-files',
            'standards/skills-commands-hooks',
            'standards/context-memory-and-rules',
            'standards/review-quality-gates',
            'standards/evaluation-risk-metrics',
            'standards/ai-development-standards',
            'standards/freshness-governance',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.architecture.label,
          link: {
            type: 'doc',
            id: 'architecture/index',
          },
          items: [
            'architecture/ai-native-engineering-architecture',
            'architecture/mcp-tool-topology',
          ],
        },
        {
          type: 'category',
          label: DOMAIN_DEFINITIONS.ecosystem.label,
          link: {
            type: 'doc',
            id: 'ecosystem/index',
          },
          items: [
            {
              type: 'category',
              label: '工具接入与治理',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'ecosystem/integrations',
                },
              ],
            },
          ],
        },
      ],
    },
  ],

  videoResourcesSidebar: [
    'tools/resources/index',
    'tools/resources/videos',
    'tools/resources/courses',
  ],

  contentIndexSidebar: [
    'overview/content-index',
    {
      type: 'category',
      label: 'Comparisons',
      link: {
        type: 'doc',
        id: 'comparisons/index',
      },
      items: [
        'comparisons/ai-coding-platform-comparison-framework',
        'comparisons/github-copilot-vs-vscode-agent-vs-openai-codex',
        'comparisons/cursor-vs-windsurf-vs-cline',
      ],
    },
    {
      type: 'category',
      label: 'Playbooks',
      link: {
        type: 'doc',
        id: 'playbooks/index',
      },
      items: [
        'playbooks/workflow-playbook',
        'playbooks/personal-engineer-stack-setup',
        'playbooks/first-7-days-ai-coding',
      ],
    },
    {
      type: 'category',
      label: 'Insights',
      link: {
        type: 'doc',
        id: 'insights/index',
      },
      items: ['insights/agentic-coding-patterns', 'insights/monthly-brief-2026-03'],
    },
  ],

  archiveSidebar: [
    'archive/index',
    {
      type: 'category',
      label: '模型与 Agent',
      link: {
        type: 'doc',
        id: 'archive/tracks/models-agents/index',
      },
      items: ['archive/tracks/models-agents/coding-models-scorecard'],
    },
    {
      type: 'category',
      label: 'IDE 与工具链',
      link: {
        type: 'doc',
        id: 'archive/tracks/ides-tooling/index',
      },
      items: ['archive/tracks/ides-tooling/review-and-pr-tooling'],
    },
    'archive/tracks/prompting-workflows/index',
    {
      type: 'category',
      label: '团队与交付',
      link: {
        type: 'doc',
        id: 'archive/tracks/team-delivery/index',
      },
      items: ['archive/tracks/team-delivery/solo-to-team-transition'],
    },
  ],

  siteAdminSidebar: [
    'site-admin/editorial-workflow',
    'site-admin/ai-writing-workflow',
    'site-admin/publish-github',
    'site-admin/site-roadmap',
    'site-admin/example-first-note',
  ],
};

module.exports = sidebars;
